### ISSUE TITLE
Finetuned Model Weights

### ISSUE THREAD

**Issue by usamayaseen-veeva** [run-llama/modal_finetune_sql#6]
Hi @jerryjliu ,

Many thanks for the great codebase. Is it possible that you can please share the fine-tuned (adapter) model weights on the hugging face model hub or provide another way to download the model weights?

Thanks!

**Comment by jerryjliu** [comment]
hey @usamayaseen-veeva! hmm good question, that's definitely possible. 

Assuming you're wiling to run the script it will cost ~$15 USD. but understand it might be more convenient to just download the weights

**Comment by usamayaseen-veeva** [comment]
@jerryjliu thanks for your response!
On AWS at least, sometimes A100 instances are not available in some regions due to high demand. The option to download weights will be super useful.

**Comment by yapnel** [comment]
I would be interested in the fine tuned model if it can be made available. Thanks
